In [1]:
import os
import numpy as np
import pandas as pd

# ---------------- Importing data from a CSV file ----------------
df = pd.read_csv("sales_data.csv")

print("Data imported successfully from 'sales_data.csv'")
print("Shape      :", df.shape)
print("Columns    :", list(df.columns))
print("Data types :")
print(df.dtypes)
df.head()

Data imported successfully from 'sales_data.csv'
Shape      : (30, 3)
Columns    : ['Product', 'Region', 'Sales']
Data types :
Product      str
Region       str
Sales      int64
dtype: object

   Product Region  Sales
0   Laptop  North  50000
1   Mobile  South  35000
2  Printer   East  25000
3   Laptop   West  45000
4   Mobile  North  40000

In [2]:
# ---------------- Importing with different read options ----------------

# (a) import only selected columns
part = pd.read_csv("sales_data.csv", usecols=["Product", "Sales"])
print("(a) usecols -> only Product and Sales imported:")
print(part.head(3))

# (b) import only the first 5 rows
small = pd.read_csv("sales_data.csv", nrows=5)
print("\n(b) nrows=5 -> rows imported :", len(small))

# (c) use a column as the index
indexed = pd.read_csv("sales_data.csv", index_col="Product")
print("\n(c) index_col='Product' :")
print(indexed.head(3))

# (d) force a data type while importing
typed = pd.read_csv("sales_data.csv", dtype={"Sales": "float64"})
print("\n(d) dtype forced -> Sales is now :", typed["Sales"].dtype)

(a) usecols -> only Product and Sales imported:
   Product  Sales
0   Laptop  50000
1   Mobile  35000
2  Printer  25000

(b) nrows=5 -> rows imported : 5

(c) index_col='Product' :
        Region  Sales
Product
Laptop   North  50000
Mobile   South  35000
Printer   East  25000

(d) dtype forced -> Sales is now : float64

In [3]:
# ---------------- Importing from a Python dictionary ----------------
data_dict = {
    "Product": ["Laptop", "Mobile", "Printer"],
    "Region": ["North", "South", "East"],
    "Sales": [50000, 35000, 25000],
}
df_dict = pd.DataFrame(data_dict)
print("DataFrame created from a dictionary:")
print(df_dict)

# ---------------- Importing from a list of lists ----------------
data_list = [["Laptop", "West", 45000],
             ["Mobile", "North", 40000],
             ["Printer", "South", 30000]]
df_list = pd.DataFrame(data_list, columns=["Product", "Region", "Sales"])
print("\nDataFrame created from a list of lists:")
print(df_list)

DataFrame created from a dictionary:
   Product Region  Sales
0   Laptop  North  50000
1   Mobile  South  35000
2  Printer   East  25000

DataFrame created from a list of lists:
   Product Region  Sales
0   Laptop   West  45000
1   Mobile  North  40000
2  Printer  South  30000

In [4]:
# ---------------- Exporting to CSV ----------------
df.to_csv("exported_sales.csv", index=False)
print("Exported to 'exported_sales.csv'")

# export without the header and with a different separator
df.to_csv("exported_sales_pipe.txt", sep="|", index=False)
print("Exported to 'exported_sales_pipe.txt' with '|' as separator")

print("\nFirst 3 lines of the exported CSV file:")
with open("exported_sales.csv") as f:
    for line in f.readlines()[:4]:
        print(line.strip())

Exported to 'exported_sales.csv'
Exported to 'exported_sales_pipe.txt' with '|' as separator

First 3 lines of the exported CSV file:
Product,Region,Sales
Laptop,North,50000
Mobile,South,35000
Printer,East,25000

In [5]:
# ---------------- Exporting to an Excel workbook ----------------
df.to_excel("exported_sales.xlsx", sheet_name="Sales", index=False)
print("Exported to 'exported_sales.xlsx'")

# writing more than one sheet into the same workbook
summary = df.groupby("Region")["Sales"].sum().reset_index()

with pd.ExcelWriter("sales_report.xlsx") as writer:
    df.to_excel(writer, sheet_name="RawData", index=False)
    summary.to_excel(writer, sheet_name="RegionSummary", index=False)

print("Exported to 'sales_report.xlsx' with 2 sheets: RawData, RegionSummary")
print("\nContent written to the RegionSummary sheet:")
print(summary)

Exported to 'exported_sales.xlsx'
Exported to 'sales_report.xlsx' with 2 sheets: RawData, RegionSummary

Content written to the RegionSummary sheet:
  Region   Sales
0   East  286000
1  North  341000
2  South  303000
3   West  271000

In [6]:
# ---------------- Exporting to JSON ----------------
df.to_json("exported_sales.json", orient="records", indent=2)
print("Exported to 'exported_sales.json'")

print("\nFirst few lines of the JSON file:")
with open("exported_sales.json") as f:
    print("".join(f.readlines()[:12]))

Exported to 'exported_sales.json'

First few lines of the JSON file:
[
  {
    "Product":"Laptop",
    "Region":"North",
    "Sales":50000
  },
  {
    "Product":"Mobile",
    "Region":"South",
    "Sales":35000
  },
  {

In [7]:
# ---------------- Exporting to HTML ----------------
df.head(5).to_html("exported_sales.html", index=False)
print("Exported to 'exported_sales.html'")

# ---------------- Exporting to a plain text file ----------------
with open("exported_sales_report.txt", "w") as f:
    f.write("SALES REPORT\n")
    f.write("=" * 34 + "\n")
    f.write(df.head(5).to_string(index=False))

print("Exported to 'exported_sales_report.txt'")
print("\nContent of the text file:")
print(open("exported_sales_report.txt").read())

Exported to 'exported_sales.html'
Exported to 'exported_sales_report.txt'

Content of the text file:
SALES REPORT
==================================
Product Region  Sales
 Laptop  North  50000
 Mobile  South  35000
Printer   East  25000
 Laptop   West  45000
 Mobile  North  40000

In [8]:
# ---------------- Listing the exported files ----------------
files = sorted(f for f in os.listdir()
               if f.startswith("exported") or f.startswith("sales"))

print("Files present in the working directory:")
for f in files:
    print(f"{f:32s} {os.path.getsize(f):8d} bytes")

Files present in the working directory:
exported_sales.csv                    587 bytes
exported_sales.html                   613 bytes
exported_sales.json                  2188 bytes
exported_sales.xlsx                  5796 bytes
exported_sales_pipe.txt               587 bytes
exported_sales_report.txt             179 bytes
sales_data.csv                        587 bytes
sales_report.xlsx                    6348 bytes

In [9]:
# ---------------- Reading the exported files back to verify ----------------
back_csv = pd.read_csv("exported_sales.csv")
back_xlsx = pd.read_excel("exported_sales.xlsx", sheet_name="Sales")
back_json = pd.read_json("exported_sales.json")
back_html = pd.read_html("exported_sales.html")[0]

print("CSV   -> shape :", back_csv.shape)
print("Excel -> shape :", back_xlsx.shape)
print("JSON  -> shape :", back_json.shape)
print("HTML  -> shape :", back_html.shape)
print("\nCSV and original data are identical :", back_csv.equals(df))
print("\nData read back from the JSON file:")
back_json.head()

CSV   -> shape : (30, 3)
Excel -> shape : (30, 3)
JSON  -> shape : (30, 3)
HTML  -> shape : (5, 3)

CSV and original data are identical : True

Data read back from the JSON file:

   Product Region  Sales
0   Laptop  North  50000
1   Mobile  South  35000
2  Printer   East  25000
3   Laptop   West  45000
4   Mobile  North  40000